version: 2.1
jobs:
  check-ov:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout:
      - run:
          name: Running CheckOV
          command: docker run --volume "${{ env.GITHUB_WORKSPACE }}":/tf bridgecrew/checkov --directory /tf --soft-fail
   terraform-check:
     docker:
      - image: ubuntu:latest
    steps:
      - checkout:
      - run: 
          name: Terraform Plan and validate
          command: |
            terraform plan -out tfplan
            terraform show -json tfplan > tfplan.json
            docker run --volume "${{ env.GITHUB_WORKSPACE }}":/tf bridgecrew/checkov -f tfplan.json --soft-fail      
workflows:
  running-checkov:
    jobs:
      - check-ov
      - terraform-check
          requires:
            - check-ov
